import { formatDate } from "../utils/authUtils";

/**
 * Posts can be added here.
 * You can add default posts of your wish with different attributes
 * */

export const posts = [
  {
    _id: "fsjfhjsdh434jhsjd3",
    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652342774/photo-1652298926911-9d628f82e7de_xnxfvn.jpg",
    content:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam veniam, voluptates illum repellendus vitae blanditiis voluptatum omnis reprehenderit corrupti officia.",
    likes: {
      likeCount: 0,
      likedBy: [
        {
          _id: "asassdafdgdk",
          firstName: "Jalaj",
          lastName: "Gupta",
          username: "jalaj@gmail.com",
          password: "test1234",
          createdAt: "2022-01-25T10:38:12+05:30",
          updatedAt: "2022-05-17T10:33:36+05:30",
          userHandler: "jalaj",
          pic: "https://picsum.photos/200",
          link: "https://jalaj.netlify.app",
          bio: "Software Developer",
          followers: [
            {
              _id: "asassddsd243434",
              firstName: "Ruchi",
              lastName: "Gupta",
              username: "ruchi@gmail.com",
              password: "test1234",
              createdAt: "2022-03-21T10:12:12+05:30",
              updatedAt: "2022-05-16T18:11:07+05:30",
              userHandler: "ruchi",
              pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
              link: "https://ruchi.netlify.app",
              bio: "Fashion Designer",
              followers: [
                {
                  _id: "asassdafdgdk",
                  firstName: "Jalaj",
                  lastName: "Gupta",
                  username: "jalaj@gmail.com",
                  password: "test1234",
                  createdAt: "2022-01-25T10:38:12+05:30",
                  updatedAt: "2022-05-14T18:08:40+05:30",
                  userHandler: "jalaj",
                  pic: "https://picsum.photos/200",
                  link: "https://jalaj.netlify.app",
                  bio: "Software Developer",
                  followers: [],
                  following: [],
                  bookmarks: [],
                  id: "1",
                },
              ],
              following: [],
              bookmarks: [],
              id: "2",
            },
            {
              _id: "asassddfdsfdgsd32323",
              firstName: "Raj",
              lastName: "Gill",
              username: "raj@gmail.com",
              password: "1234asdf",
              createdAt: "2022-05-12T08:30:12+05:30",
              updatedAt: "2022-05-16T18:11:32+05:30",
              userHandler: "raj",
              pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
              link: "https://raj.netlify.app",
              bio: "Web Designer",
              followers: [
                {
                  _id: "asassdafdgdk",
                  firstName: "Jalaj",
                  lastName: "Gupta",
                  username: "jalaj@gmail.com",
                  password: "test1234",
                  createdAt: "2022-01-25T10:38:12+05:30",
                  updatedAt: "2022-05-16T18:11:07+05:30",
                  userHandler: "jalaj",
                  pic: "https://picsum.photos/200",
                  link: "https://jalaj.netlify.app",
                  bio: "Software Developer",
                  followers: [],
                  following: [
                    {
                      _id: "asassddsd243434",
                      firstName: "Ruchi",
                      lastName: "Gupta",
                      username: "ruchi@gmail.com",
                      password: "test1234",
                      createdAt: "2022-03-21T10:12:12+05:30",
                      updatedAt: "2022-05-14T18:10:33+05:30",
                      userHandler: "ruchi",
                      pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                      link: "https://ruchi.netlify.app",
                      bio: "Fashion Designer",
                      followers: [],
                      following: [],
                      bookmarks: [],
                      id: "2",
                    },
                  ],
                  bookmarks: [],
                  id: "1",
                },
              ],
              following: [],
              bookmarks: [],
              id: "3",
            },
          ],
          following: [
            {
              _id: "asassddsd243434",
              firstName: "Ruchi",
              lastName: "Gupta",
              username: "ruchi@gmail.com",
              password: "test1234",
              createdAt: "2022-03-21T10:12:12+05:30",
              updatedAt: "2022-05-14T18:10:33+05:30",
              userHandler: "ruchi",
              pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
              link: "https://ruchi.netlify.app",
              bio: "Fashion Designer",
              followers: [],
              following: [],
              bookmarks: [],
              id: "2",
            },
            {
              _id: "asassddfdsfdgsd32323",
              firstName: "Raj",
              lastName: "Gill",
              username: "raj@gmail.com",
              password: "1234asdf",
              createdAt: "2022-05-12T08:30:12+05:30",
              updatedAt: "2022-05-14T18:11:48+05:30",
              userHandler: "raj",
              pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
              link: "https://raj.netlify.app",
              bio: "Web Designer",
              followers: [],
              following: [],
              bookmarks: [],
              id: "3",
            },
          ],
          bookmarks: [],
          id: "1",
        },
        {
          _id: "asassddsd243434",
          firstName: "Ruchi",
          lastName: "Gupta",
          username: "ruchi@gmail.com",
          password: "test1234",
          createdAt: "2022-03-21T10:12:12+05:30",
          updatedAt: "2022-05-17T11:07:58+05:30",
          userHandler: "ruchi",
          pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
          link: "https://ruchi.netlify.app",
          bio: "Fashion Designer",
          followers: [
            {
              _id: "asassdafdgdk",
              firstName: "Jalaj",
              lastName: "Gupta",
              username: "jalaj@gmail.com",
              password: "test1234",
              createdAt: "2022-01-25T10:38:12+05:30",
              updatedAt: "2022-05-14T18:08:40+05:30",
              userHandler: "jalaj",
              pic: "https://picsum.photos/200",
              link: "https://jalaj.netlify.app",
              bio: "Software Developer",
              followers: [],
              following: [],
              bookmarks: [],
              id: "1",
            },
            {
              _id: "asassddfd232fgfg323",
              firstName: "Tanvi",
              lastName: "Sharma",
              username: "tanvi@gmail.com",
              password: "1234asdf",
              createdAt: "2022-04-09T09:30:12+05:30",
              updatedAt: "2022-05-16T18:13:02+05:30",
              userHandler: "tanvi",
              pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652427968/images_dmm7fi.jpg",
              link: "https://tanvi.netlify.app",
              bio: "Web Developer",
              followers: [
                {
                  _id: "asassddsd243434",
                  firstName: "Ruchi",
                  lastName: "Gupta",
                  username: "ruchi@gmail.com",
                  password: "test1234",
                  createdAt: "2022-03-21T10:12:12+05:30",
                  updatedAt: "2022-05-16T18:12:59+05:30",
                  userHandler: "ruchi",
                  pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                  link: "https://ruchi.netlify.app",
                  bio: "Fashion Designer",
                  followers: [
                    {
                      _id: "asassdafdgdk",
                      firstName: "Jalaj",
                      lastName: "Gupta",
                      username: "jalaj@gmail.com",
                      password: "test1234",
                      createdAt: "2022-01-25T10:38:12+05:30",
                      updatedAt: "2022-05-14T18:08:40+05:30",
                      userHandler: "jalaj",
                      pic: "https://picsum.photos/200",
                      link: "https://jalaj.netlify.app",
                      bio: "Software Developer",
                      followers: [],
                      following: [],
                      bookmarks: [],
                      id: "1",
                    },
                  ],
                  following: [
                    {
                      _id: "asassdafdgdk",
                      firstName: "Jalaj",
                      lastName: "Gupta",
                      username: "jalaj@gmail.com",
                      password: "test1234",
                      createdAt: "2022-01-25T10:38:12+05:30",
                      updatedAt: "2022-05-16T18:11:33+05:30",
                      userHandler: "jalaj",
                      pic: "https://picsum.photos/200",
                      link: "https://jalaj.netlify.app",
                      bio: "Software Developer",
                      followers: [],
                      following: [
                        {
                          _id: "asassddsd243434",
                          firstName: "Ruchi",
                          lastName: "Gupta",
                          username: "ruchi@gmail.com",
                          password: "test1234",
                          createdAt: "2022-03-21T10:12:12+05:30",
                          updatedAt: "2022-05-14T18:10:33+05:30",
                          userHandler: "ruchi",
                          pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                          link: "https://ruchi.netlify.app",
                          bio: "Fashion Designer",
                          followers: [],
                          following: [],
                          bookmarks: [],
                          id: "2",
                        },
                        {
                          _id: "asassddfdsfdgsd32323",
                          firstName: "Raj",
                          lastName: "Gill",
                          username: "raj@gmail.com",
                          password: "1234asdf",
                          createdAt: "2022-05-12T08:30:12+05:30",
                          updatedAt: "2022-05-14T18:11:48+05:30",
                          userHandler: "raj",
                          pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
                          link: "https://raj.netlify.app",
                          bio: "Web Designer",
                          followers: [],
                          following: [],
                          bookmarks: [],
                          id: "3",
                        },
                      ],
                      bookmarks: [],
                      id: "1",
                    },
                  ],
                  bookmarks: [],
                  id: "2",
                },
              ],
              following: [],
              bookmarks: [],
              id: "4",
            },
            {
              _id: "asassddfdsfdgsd32323",
              firstName: "Raj",
              lastName: "Gill",
              username: "raj@gmail.com",
              password: "1234asdf",
              createdAt: "2022-05-12T08:30:12+05:30",
              updatedAt: "2022-05-17T11:05:59+05:30",
              userHandler: "raj",
              pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
              link: "https://raj.netlify.app",
              bio: "Web Designer",
              followers: [
                {
                  _id: "asassdafdgdk",
                  firstName: "Jalaj",
                  lastName: "Gupta",
                  username: "jalaj@gmail.com",
                  password: "test1234",
                  createdAt: "2022-01-25T10:38:12+05:30",
                  updatedAt: "2022-05-16T18:11:07+05:30",
                  userHandler: "jalaj",
                  pic: "https://picsum.photos/200",
                  link: "https://jalaj.netlify.app",
                  bio: "Software Developer",
                  followers: [],
                  following: [
                    {
                      _id: "asassddsd243434",
                      firstName: "Ruchi",
                      lastName: "Gupta",
                      username: "ruchi@gmail.com",
                      password: "test1234",
                      createdAt: "2022-03-21T10:12:12+05:30",
                      updatedAt: "2022-05-14T18:10:33+05:30",
                      userHandler: "ruchi",
                      pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                      link: "https://ruchi.netlify.app",
                      bio: "Fashion Designer",
                      followers: [],
                      following: [],
                      bookmarks: [],
                      id: "2",
                    },
                  ],
                  bookmarks: [],
                  id: "1",
                },
                {
                  _id: "asassddsd243434",
                  firstName: "Ruchi",
                  lastName: "Gupta",
                  username: "ruchi@gmail.com",
                  password: "test1234",
                  createdAt: "2022-03-21T10:12:12+05:30",
                  updatedAt: "2022-05-17T10:24:05+05:30",
                  userHandler: "ruchi",
                  pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                  link: "https://ruchi.netlify.app",
                  bio: "Fashion Designer",
                  followers: [
                    {
                      _id: "asassdafdgdk",
                      firstName: "Jalaj",
                      lastName: "Gupta",
                      username: "jalaj@gmail.com",
                      password: "test1234",
                      createdAt: "2022-01-25T10:38:12+05:30",
                      updatedAt: "2022-05-14T18:08:40+05:30",
                      userHandler: "jalaj",
                      pic: "https://picsum.photos/200",
                      link: "https://jalaj.netlify.app",
                      bio: "Software Developer",
                      followers: [],
                      following: [],
                      bookmarks: [],
                      id: "1",
                    },
                  ],
                  following: [
                    {
                      _id: "asassdafdgdk",
                      firstName: "Jalaj",
                      lastName: "Gupta",
                      username: "jalaj@gmail.com",
                      password: "test1234",
                      createdAt: "2022-01-25T10:38:12+05:30",
                      updatedAt: "2022-05-16T18:11:33+05:30",
                      userHandler: "jalaj",
                      pic: "https://picsum.photos/200",
                      link: "https://jalaj.netlify.app",
                      bio: "Software Developer",
                      followers: [],
                      following: [
                        {
                          _id: "asassddsd243434",
                          firstName: "Ruchi",
                          lastName: "Gupta",
                          username: "ruchi@gmail.com",
                          password: "test1234",
                          createdAt: "2022-03-21T10:12:12+05:30",
                          updatedAt: "2022-05-14T18:10:33+05:30",
                          userHandler: "ruchi",
                          pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                          link: "https://ruchi.netlify.app",
                          bio: "Fashion Designer",
                          followers: [],
                          following: [],
                          bookmarks: [],
                          id: "2",
                        },
                        {
                          _id: "asassddfdsfdgsd32323",
                          firstName: "Raj",
                          lastName: "Gill",
                          username: "raj@gmail.com",
                          password: "1234asdf",
                          createdAt: "2022-05-12T08:30:12+05:30",
                          updatedAt: "2022-05-14T18:11:48+05:30",
                          userHandler: "raj",
                          pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
                          link: "https://raj.netlify.app",
                          bio: "Web Designer",
                          followers: [],
                          following: [],
                          bookmarks: [],
                          id: "3",
                        },
                      ],
                      bookmarks: [],
                      id: "1",
                    },
                    {
                      _id: "asassddfd232fgfg323",
                      firstName: "Tanvi",
                      lastName: "Sharma",
                      username: "tanvi@gmail.com",
                      password: "1234asdf",
                      createdAt: "2022-04-09T09:30:12+05:30",
                      updatedAt: "2022-05-14T18:12:29+05:30",
                      userHandler: "tanvi",
                      pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652427968/images_dmm7fi.jpg",
                      link: "https://tanvi.netlify.app",
                      bio: "Web Developer",
                      followers: [],
                      following: [],
                      bookmarks: [],
                      id: "4",
                    },
                    {
                      _id: "asassddfd232fg23ssfdf",
                      firstName: "Navodita",
                      lastName: "Shah",
                      username: "navj@gmail.com",
                      password: "1234asdf",
                      createdAt: "2022-02-10T09:30:12+05:30",
                      updatedAt: "2022-05-16T18:11:01+05:30",
                      userHandler: "navjj",
                      pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652427577/ro2zurljoctvqo2kwyya.jpg",
                      link: "https://navjj.netlify.app",
                      bio: "Mobile Developer",
                      followers: [],
                      following: [],
                      bookmarks: [],
                      id: "5",
                    },
                  ],
                  bookmarks: [],
                  id: "2",
                },
              ],
              following: [
                {
                  _id: "asassdafdgdk",
                  firstName: "Jalaj",
                  lastName: "Gupta",
                  username: "jalaj@gmail.com",
                  password: "test1234",
                  createdAt: "2022-01-25T10:38:12+05:30",
                  updatedAt: "2022-05-16T18:12:59+05:30",
                  userHandler: "jalaj",
                  pic: "https://picsum.photos/200",
                  link: "https://jalaj.netlify.app",
                  bio: "Software Developer",
                  followers: [
                    {
                      _id: "asassddsd243434",
                      firstName: "Ruchi",
                      lastName: "Gupta",
                      username: "ruchi@gmail.com",
                      password: "test1234",
                      createdAt: "2022-03-21T10:12:12+05:30",
                      updatedAt: "2022-05-16T18:11:07+05:30",
                      userHandler: "ruchi",
                      pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                      link: "https://ruchi.netlify.app",
                      bio: "Fashion Designer",
                      followers: [
                        {
                          _id: "asassdafdgdk",
                          firstName: "Jalaj",
                          lastName: "Gupta",
                          username: "jalaj@gmail.com",
                          password: "test1234",
                          createdAt: "2022-01-25T10:38:12+05:30",
                          updatedAt: "2022-05-14T18:08:40+05:30",
                          userHandler: "jalaj",
                          pic: "https://picsum.photos/200",
                          link: "https://jalaj.netlify.app",
                          bio: "Software Developer",
                          followers: [],
                          following: [],
                          bookmarks: [],
                          id: "1",
                        },
                      ],
                      following: [],
                      bookmarks: [],
                      id: "2",
                    },
                  ],
                  following: [
                    {
                      _id: "asassddsd243434",
                      firstName: "Ruchi",
                      lastName: "Gupta",
                      username: "ruchi@gmail.com",
                      password: "test1234",
                      createdAt: "2022-03-21T10:12:12+05:30",
                      updatedAt: "2022-05-14T18:10:33+05:30",
                      userHandler: "ruchi",
                      pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                      link: "https://ruchi.netlify.app",
                      bio: "Fashion Designer",
                      followers: [],
                      following: [],
                      bookmarks: [],
                      id: "2",
                    },
                    {
                      _id: "asassddfdsfdgsd32323",
                      firstName: "Raj",
                      lastName: "Gill",
                      username: "raj@gmail.com",
                      password: "1234asdf",
                      createdAt: "2022-05-12T08:30:12+05:30",
                      updatedAt: "2022-05-14T18:11:48+05:30",
                      userHandler: "raj",
                      pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
                      link: "https://raj.netlify.app",
                      bio: "Web Designer",
                      followers: [],
                      following: [],
                      bookmarks: [],
                      id: "3",
                    },
                  ],
                  bookmarks: [],
                  id: "1",
                },
              ],
              bookmarks: [],
              id: "3",
            },
          ],
          following: [
            {
              _id: "asassdafdgdk",
              firstName: "Jalaj",
              lastName: "Gupta",
              username: "jalaj@gmail.com",
              password: "test1234",
              createdAt: "2022-01-25T10:38:12+05:30",
              updatedAt: "2022-05-16T18:11:33+05:30",
              userHandler: "jalaj",
              pic: "https://picsum.photos/200",
              link: "https://jalaj.netlify.app",
              bio: "Software Developer",
              followers: [],
              following: [
                {
                  _id: "asassddsd243434",
                  firstName: "Ruchi",
                  lastName: "Gupta",
                  username: "ruchi@gmail.com",
                  password: "test1234",
                  createdAt: "2022-03-21T10:12:12+05:30",
                  updatedAt: "2022-05-14T18:10:33+05:30",
                  userHandler: "ruchi",
                  pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                  link: "https://ruchi.netlify.app",
                  bio: "Fashion Designer",
                  followers: [],
                  following: [],
                  bookmarks: [],
                  id: "2",
                },
                {
                  _id: "asassddfdsfdgsd32323",
                  firstName: "Raj",
                  lastName: "Gill",
                  username: "raj@gmail.com",
                  password: "1234asdf",
                  createdAt: "2022-05-12T08:30:12+05:30",
                  updatedAt: "2022-05-14T18:11:48+05:30",
                  userHandler: "raj",
                  pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
                  link: "https://raj.netlify.app",
                  bio: "Web Designer",
                  followers: [],
                  following: [],
                  bookmarks: [],
                  id: "3",
                },
              ],
              bookmarks: [],
              id: "1",
            },
            {
              _id: "asassddfd232fgfg323",
              firstName: "Tanvi",
              lastName: "Sharma",
              username: "tanvi@gmail.com",
              password: "1234asdf",
              createdAt: "2022-04-09T09:30:12+05:30",
              updatedAt: "2022-05-14T18:12:29+05:30",
              userHandler: "tanvi",
              pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652427968/images_dmm7fi.jpg",
              link: "https://tanvi.netlify.app",
              bio: "Web Developer",
              followers: [],
              following: [],
              bookmarks: [],
              id: "4",
            },
            {
              _id: "asassddfd232fg23ssfdf",
              firstName: "Navodita",
              lastName: "Shah",
              username: "navj@gmail.com",
              password: "1234asdf",
              createdAt: "2022-02-10T09:30:12+05:30",
              updatedAt: "2022-05-16T18:11:01+05:30",
              userHandler: "navjj",
              pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652427577/ro2zurljoctvqo2kwyya.jpg",
              link: "https://navjj.netlify.app",
              bio: "Mobile Developer",
              followers: [],
              following: [],
              bookmarks: [],
              id: "5",
            },
            {
              _id: "asassddfdsfdgsd32323",
              firstName: "Raj",
              lastName: "Gill",
              username: "raj@gmail.com",
              password: "1234asdf",
              createdAt: "2022-05-12T08:30:12+05:30",
              updatedAt: "2022-05-16T18:14:29+05:30",
              userHandler: "raj",
              pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
              link: "https://raj.netlify.app",
              bio: "Web Designer",
              followers: [
                {
                  _id: "asassdafdgdk",
                  firstName: "Jalaj",
                  lastName: "Gupta",
                  username: "jalaj@gmail.com",
                  password: "test1234",
                  createdAt: "2022-01-25T10:38:12+05:30",
                  updatedAt: "2022-05-16T18:11:07+05:30",
                  userHandler: "jalaj",
                  pic: "https://picsum.photos/200",
                  link: "https://jalaj.netlify.app",
                  bio: "Software Developer",
                  followers: [],
                  following: [
                    {
                      _id: "asassddsd243434",
                      firstName: "Ruchi",
                      lastName: "Gupta",
                      username: "ruchi@gmail.com",
                      password: "test1234",
                      createdAt: "2022-03-21T10:12:12+05:30",
                      updatedAt: "2022-05-14T18:10:33+05:30",
                      userHandler: "ruchi",
                      pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                      link: "https://ruchi.netlify.app",
                      bio: "Fashion Designer",
                      followers: [],
                      following: [],
                      bookmarks: [],
                      id: "2",
                    },
                  ],
                  bookmarks: [],
                  id: "1",
                },
              ],
              following: [
                {
                  _id: "asassdafdgdk",
                  firstName: "Jalaj",
                  lastName: "Gupta",
                  username: "jalaj@gmail.com",
                  password: "test1234",
                  createdAt: "2022-01-25T10:38:12+05:30",
                  updatedAt: "2022-05-16T18:12:59+05:30",
                  userHandler: "jalaj",
                  pic: "https://picsum.photos/200",
                  link: "https://jalaj.netlify.app",
                  bio: "Software Developer",
                  followers: [
                    {
                      _id: "asassddsd243434",
                      firstName: "Ruchi",
                      lastName: "Gupta",
                      username: "ruchi@gmail.com",
                      password: "test1234",
                      createdAt: "2022-03-21T10:12:12+05:30",
                      updatedAt: "2022-05-16T18:11:07+05:30",
                      userHandler: "ruchi",
                      pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                      link: "https://ruchi.netlify.app",
                      bio: "Fashion Designer",
                      followers: [
                        {
                          _id: "asassdafdgdk",
                          firstName: "Jalaj",
                          lastName: "Gupta",
                          username: "jalaj@gmail.com",
                          password: "test1234",
                          createdAt: "2022-01-25T10:38:12+05:30",
                          updatedAt: "2022-05-14T18:08:40+05:30",
                          userHandler: "jalaj",
                          pic: "https://picsum.photos/200",
                          link: "https://jalaj.netlify.app",
                          bio: "Software Developer",
                          followers: [],
                          following: [],
                          bookmarks: [],
                          id: "1",
                        },
                      ],
                      following: [],
                      bookmarks: [],
                      id: "2",
                    },
                  ],
                  following: [
                    {
                      _id: "asassddsd243434",
                      firstName: "Ruchi",
                      lastName: "Gupta",
                      username: "ruchi@gmail.com",
                      password: "test1234",
                      createdAt: "2022-03-21T10:12:12+05:30",
                      updatedAt: "2022-05-14T18:10:33+05:30",
                      userHandler: "ruchi",
                      pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                      link: "https://ruchi.netlify.app",
                      bio: "Fashion Designer",
                      followers: [],
                      following: [],
                      bookmarks: [],
                      id: "2",
                    },
                    {
                      _id: "asassddfdsfdgsd32323",
                      firstName: "Raj",
                      lastName: "Gill",
                      username: "raj@gmail.com",
                      password: "1234asdf",
                      createdAt: "2022-05-12T08:30:12+05:30",
                      updatedAt: "2022-05-14T18:11:48+05:30",
                      userHandler: "raj",
                      pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
                      link: "https://raj.netlify.app",
                      bio: "Web Designer",
                      followers: [],
                      following: [],
                      bookmarks: [],
                      id: "3",
                    },
                  ],
                  bookmarks: [],
                  id: "1",
                },
              ],
              bookmarks: [],
              id: "3",
            },
          ],
          bookmarks: [],
          id: "2",
        },
      ],
      dislikedBy: [],
    },
    comments: [],
    userId: "asassdafdgdk",
    createdAt: "2022-01-25T10:38:12+05:30",
    updatedAt: formatDate(),
  },
  {
    _id: "343asa232sfdgt45",
    content:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas, esse.",
    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652342874/photo-1652335223113-9919b4e052d5_ecguab.jpg",
    likes: {
      likeCount: 0,
      likedBy: [],
      dislikedBy: [],
    },
    comments: [],
    userId: "asassdafdgdk",
    createdAt: "2022-01-25T10:38:12+05:30",
    updatedAt: formatDate(),
  },
];
