import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */
export const users = [
  {
    _id: "asassdafdgdk",
    firstName: "Jalaj",
    lastName: "Gupta",
    username: "jalaj@gmail.com",
    password: "test1234",
    createdAt: "2022-01-25T10:38:12+05:30",
    updatedAt: "2022-05-17T10:33:36+05:30",
    userHandler: "jalaj",
    pic: "https://picsum.photos/200",
    link: "https://jalaj.netlify.app",
    bio: "Software Developer",
    followers: [
      {
        _id: "asassddsd243434",
        firstName: "Ruchi",
        lastName: "Gupta",
        username: "ruchi@gmail.com",
        password: "test1234",
        createdAt: "2022-03-21T10:12:12+05:30",
        updatedAt: "2022-05-16T18:11:07+05:30",
        userHandler: "ruchi",
        pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
        link: "https://ruchi.netlify.app",
        bio: "Fashion Designer",
        followers: [
          {
            _id: "asassdafdgdk",
            firstName: "Jalaj",
            lastName: "Gupta",
            username: "jalaj@gmail.com",
            password: "test1234",
            createdAt: "2022-01-25T10:38:12+05:30",
            updatedAt: "2022-05-14T18:08:40+05:30",
            userHandler: "jalaj",
            pic: "https://picsum.photos/200",
            link: "https://jalaj.netlify.app",
            bio: "Software Developer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "1",
          },
        ],
        following: [],
        bookmarks: [],
        id: "2",
      },
      {
        _id: "asassddfdsfdgsd32323",
        firstName: "Raj",
        lastName: "Singh",
        username: "raj@gmail.com",
        password: "1234asdf",
        createdAt: "2022-05-12T08:30:12+05:30",
        updatedAt: "2022-05-16T18:11:32+05:30",
        userHandler: "raj",
        pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
        link: "https://raj.netlify.app",
        bio: "Web Designer",
        followers: [
          {
            _id: "asassdafdgdk",
            firstName: "Jalaj",
            lastName: "Gupta",
            username: "jalaj@gmail.com",
            password: "test1234",
            createdAt: "2022-01-25T10:38:12+05:30",
            updatedAt: "2022-05-16T18:11:07+05:30",
            userHandler: "jalaj",
            pic: "https://picsum.photos/200",
            link: "https://jalaj.netlify.app",
            bio: "Software Developer",
            followers: [],
            following: [
              {
                _id: "asassddsd243434",
                firstName: "Ruchi",
                lastName: "Gupta",
                username: "ruchi@gmail.com",
                password: "test1234",
                createdAt: "2022-03-21T10:12:12+05:30",
                updatedAt: "2022-05-14T18:10:33+05:30",
                userHandler: "ruchi",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                link: "https://ruchi.netlify.app",
                bio: "Fashion Designer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "2",
              },
            ],
            bookmarks: [],
            id: "1",
          },
        ],
        following: [],
        bookmarks: [],
        id: "3",
      },
    ],
    following: [
      {
        _id: "asassddsd243434",
        firstName: "Ruchi",
        lastName: "Gupta",
        username: "ruchi@gmail.com",
        password: "test1234",
        createdAt: "2022-03-21T10:12:12+05:30",
        updatedAt: "2022-05-14T18:10:33+05:30",
        userHandler: "ruchi",
        pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
        link: "https://ruchi.netlify.app",
        bio: "Fashion Designer",
        followers: [],
        following: [],
        bookmarks: [],
        id: "2",
      },
      {
        _id: "asassddfdsfdgsd32323",
        firstName: "Raj",
        lastName: "Singh",
        username: "raj@gmail.com",
        password: "1234asdf",
        createdAt: "2022-05-12T08:30:12+05:30",
        updatedAt: "2022-05-14T18:11:48+05:30",
        userHandler: "raj",
        pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
        link: "https://raj.netlify.app",
        bio: "Web Designer",
        followers: [],
        following: [],
        bookmarks: [],
        id: "3",
      },
    ],
    bookmarks: [],
    id: "1",
  },
  {
    _id: "asassddsd243434",
    firstName: "Ruchi",
    lastName: "Gupta",
    username: "ruchi@gmail.com",
    password: "test1234",
    createdAt: "2022-03-21T10:12:12+05:30",
    updatedAt: "2022-05-17T11:07:58+05:30",
    userHandler: "ruchi",
    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
    link: "https://ruchi.netlify.app",
    bio: "Fashion Designer",
    followers: [
      {
        _id: "asassdafdgdk",
        firstName: "Jalaj",
        lastName: "Gupta",
        username: "jalaj@gmail.com",
        password: "test1234",
        createdAt: "2022-01-25T10:38:12+05:30",
        updatedAt: "2022-05-14T18:08:40+05:30",
        userHandler: "jalaj",
        pic: "https://picsum.photos/200",
        link: "https://jalaj.netlify.app",
        bio: "Software Developer",
        followers: [],
        following: [],
        bookmarks: [],
        id: "1",
      },
      {
        _id: "asassddfd232fgfg323",
        firstName: "Tanvi",
        lastName: "Sharma",
        username: "tanvi@gmail.com",
        password: "1234asdf",
        createdAt: "2022-04-09T09:30:12+05:30",
        updatedAt: "2022-05-16T18:13:02+05:30",
        userHandler: "tanvi",
        pic: "https://robohash.org/rerumperferendisaccusamus.png?size=300x300&set=set1",
        link: "https://tanvi.netlify.app",
        bio: "Web Developer",
        followers: [
          {
            _id: "asassddsd243434",
            firstName: "Ruchi",
            lastName: "Gupta",
            username: "ruchi@gmail.com",
            password: "test1234",
            createdAt: "2022-03-21T10:12:12+05:30",
            updatedAt: "2022-05-16T18:12:59+05:30",
            userHandler: "ruchi",
            pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
            link: "https://ruchi.netlify.app",
            bio: "Fashion Designer",
            followers: [
              {
                _id: "asassdafdgdk",
                firstName: "Jalaj",
                lastName: "Gupta",
                username: "jalaj@gmail.com",
                password: "test1234",
                createdAt: "2022-01-25T10:38:12+05:30",
                updatedAt: "2022-05-14T18:08:40+05:30",
                userHandler: "jalaj",
                pic: "https://picsum.photos/200",
                link: "https://jalaj.netlify.app",
                bio: "Software Developer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "1",
              },
            ],
            following: [
              {
                _id: "asassdafdgdk",
                firstName: "Jalaj",
                lastName: "Gupta",
                username: "jalaj@gmail.com",
                password: "test1234",
                createdAt: "2022-01-25T10:38:12+05:30",
                updatedAt: "2022-05-16T18:11:33+05:30",
                userHandler: "jalaj",
                pic: "https://picsum.photos/200",
                link: "https://jalaj.netlify.app",
                bio: "Software Developer",
                followers: [],
                following: [
                  {
                    _id: "asassddsd243434",
                    firstName: "Ruchi",
                    lastName: "Gupta",
                    username: "ruchi@gmail.com",
                    password: "test1234",
                    createdAt: "2022-03-21T10:12:12+05:30",
                    updatedAt: "2022-05-14T18:10:33+05:30",
                    userHandler: "ruchi",
                    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                    link: "https://ruchi.netlify.app",
                    bio: "Fashion Designer",
                    followers: [],
                    following: [],
                    bookmarks: [],
                    id: "2",
                  },
                  {
                    _id: "asassddfdsfdgsd32323",
                    firstName: "Raj",
                    lastName: "Singh",
                    username: "raj@gmail.com",
                    password: "1234asdf",
                    createdAt: "2022-05-12T08:30:12+05:30",
                    updatedAt: "2022-05-14T18:11:48+05:30",
                    userHandler: "raj",
                    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
                    link: "https://raj.netlify.app",
                    bio: "Web Designer",
                    followers: [],
                    following: [],
                    bookmarks: [],
                    id: "3",
                  },
                ],
                bookmarks: [],
                id: "1",
              },
            ],
            bookmarks: [],
            id: "2",
          },
        ],
        following: [],
        bookmarks: [],
        id: "4",
      },
      {
        _id: "asassddfdsfdgsd32323",
        firstName: "Raj",
        lastName: "Singh",
        username: "raj@gmail.com",
        password: "1234asdf",
        createdAt: "2022-05-12T08:30:12+05:30",
        updatedAt: "2022-05-17T11:05:59+05:30",
        userHandler: "raj",
        pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
        link: "https://raj.netlify.app",
        bio: "Web Designer",
        followers: [
          {
            _id: "asassdafdgdk",
            firstName: "Jalaj",
            lastName: "Gupta",
            username: "jalaj@gmail.com",
            password: "test1234",
            createdAt: "2022-01-25T10:38:12+05:30",
            updatedAt: "2022-05-16T18:11:07+05:30",
            userHandler: "jalaj",
            pic: "https://picsum.photos/200",
            link: "https://jalaj.netlify.app",
            bio: "Software Developer",
            followers: [],
            following: [
              {
                _id: "asassddsd243434",
                firstName: "Ruchi",
                lastName: "Gupta",
                username: "ruchi@gmail.com",
                password: "test1234",
                createdAt: "2022-03-21T10:12:12+05:30",
                updatedAt: "2022-05-14T18:10:33+05:30",
                userHandler: "ruchi",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                link: "https://ruchi.netlify.app",
                bio: "Fashion Designer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "2",
              },
            ],
            bookmarks: [],
            id: "1",
          },
          {
            _id: "asassddsd243434",
            firstName: "Ruchi",
            lastName: "Gupta",
            username: "ruchi@gmail.com",
            password: "test1234",
            createdAt: "2022-03-21T10:12:12+05:30",
            updatedAt: "2022-05-17T10:24:05+05:30",
            userHandler: "ruchi",
            pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
            link: "https://ruchi.netlify.app",
            bio: "Fashion Designer",
            followers: [
              {
                _id: "asassdafdgdk",
                firstName: "Jalaj",
                lastName: "Gupta",
                username: "jalaj@gmail.com",
                password: "test1234",
                createdAt: "2022-01-25T10:38:12+05:30",
                updatedAt: "2022-05-14T18:08:40+05:30",
                userHandler: "jalaj",
                pic: "https://picsum.photos/200",
                link: "https://jalaj.netlify.app",
                bio: "Software Developer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "1",
              },
            ],
            following: [
              {
                _id: "asassdafdgdk",
                firstName: "Jalaj",
                lastName: "Gupta",
                username: "jalaj@gmail.com",
                password: "test1234",
                createdAt: "2022-01-25T10:38:12+05:30",
                updatedAt: "2022-05-16T18:11:33+05:30",
                userHandler: "jalaj",
                pic: "https://picsum.photos/200",
                link: "https://jalaj.netlify.app",
                bio: "Software Developer",
                followers: [],
                following: [
                  {
                    _id: "asassddsd243434",
                    firstName: "Ruchi",
                    lastName: "Gupta",
                    username: "ruchi@gmail.com",
                    password: "test1234",
                    createdAt: "2022-03-21T10:12:12+05:30",
                    updatedAt: "2022-05-14T18:10:33+05:30",
                    userHandler: "ruchi",
                    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                    link: "https://ruchi.netlify.app",
                    bio: "Fashion Designer",
                    followers: [],
                    following: [],
                    bookmarks: [],
                    id: "2",
                  },
                  {
                    _id: "asassddfdsfdgsd32323",
                    firstName: "Raj",
                    lastName: "Singh",
                    username: "raj@gmail.com",
                    password: "1234asdf",
                    createdAt: "2022-05-12T08:30:12+05:30",
                    updatedAt: "2022-05-14T18:11:48+05:30",
                    userHandler: "raj",
                    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
                    link: "https://raj.netlify.app",
                    bio: "Web Designer",
                    followers: [],
                    following: [],
                    bookmarks: [],
                    id: "3",
                  },
                ],
                bookmarks: [],
                id: "1",
              },
              {
                _id: "asassddfd232fgfg323",
                firstName: "Tanvi",
                lastName: "Sharma",
                username: "tanvi@gmail.com",
                password: "1234asdf",
                createdAt: "2022-04-09T09:30:12+05:30",
                updatedAt: "2022-05-14T18:12:29+05:30",
                userHandler: "tanvi",
                pic: "https://robohash.org/rerumperferendisaccusamus.png?size=300x300&set=set1",
                link: "https://tanvi.netlify.app",
                bio: "Web Developer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "4",
              },
              {
                _id: "asassddfd232fg23ssfdf",
                firstName: "Navodita",
                lastName: "Shah",
                username: "navj@gmail.com",
                password: "1234asdf",
                createdAt: "2022-02-10T09:30:12+05:30",
                updatedAt: "2022-05-16T18:11:01+05:30",
                userHandler: "navjj",
                pic: "https://randomuser.me/api/portraits/women/49.jpg",
                link: "https://navjj.netlify.app",
                bio: "Mobile Developer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "5",
              },
            ],
            bookmarks: [],
            id: "2",
          },
        ],
        following: [
          {
            _id: "asassdafdgdk",
            firstName: "Jalaj",
            lastName: "Gupta",
            username: "jalaj@gmail.com",
            password: "test1234",
            createdAt: "2022-01-25T10:38:12+05:30",
            updatedAt: "2022-05-16T18:12:59+05:30",
            userHandler: "jalaj",
            pic: "https://picsum.photos/200",
            link: "https://jalaj.netlify.app",
            bio: "Software Developer",
            followers: [
              {
                _id: "asassddsd243434",
                firstName: "Ruchi",
                lastName: "Gupta",
                username: "ruchi@gmail.com",
                password: "test1234",
                createdAt: "2022-03-21T10:12:12+05:30",
                updatedAt: "2022-05-16T18:11:07+05:30",
                userHandler: "ruchi",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                link: "https://ruchi.netlify.app",
                bio: "Fashion Designer",
                followers: [
                  {
                    _id: "asassdafdgdk",
                    firstName: "Jalaj",
                    lastName: "Gupta",
                    username: "jalaj@gmail.com",
                    password: "test1234",
                    createdAt: "2022-01-25T10:38:12+05:30",
                    updatedAt: "2022-05-14T18:08:40+05:30",
                    userHandler: "jalaj",
                    pic: "https://picsum.photos/200",
                    link: "https://jalaj.netlify.app",
                    bio: "Software Developer",
                    followers: [],
                    following: [],
                    bookmarks: [],
                    id: "1",
                  },
                ],
                following: [],
                bookmarks: [],
                id: "2",
              },
            ],
            following: [
              {
                _id: "asassddsd243434",
                firstName: "Ruchi",
                lastName: "Gupta",
                username: "ruchi@gmail.com",
                password: "test1234",
                createdAt: "2022-03-21T10:12:12+05:30",
                updatedAt: "2022-05-14T18:10:33+05:30",
                userHandler: "ruchi",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                link: "https://ruchi.netlify.app",
                bio: "Fashion Designer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "2",
              },
              {
                _id: "asassddfdsfdgsd32323",
                firstName: "Raj",
                lastName: "Singh",
                username: "raj@gmail.com",
                password: "1234asdf",
                createdAt: "2022-05-12T08:30:12+05:30",
                updatedAt: "2022-05-14T18:11:48+05:30",
                userHandler: "raj",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
                link: "https://raj.netlify.app",
                bio: "Web Designer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "3",
              },
            ],
            bookmarks: [],
            id: "1",
          },
        ],
        bookmarks: [],
        id: "3",
      },
    ],
    following: [
      {
        _id: "asassdafdgdk",
        firstName: "Jalaj",
        lastName: "Gupta",
        username: "jalaj@gmail.com",
        password: "test1234",
        createdAt: "2022-01-25T10:38:12+05:30",
        updatedAt: "2022-05-16T18:11:33+05:30",
        userHandler: "jalaj",
        pic: "https://picsum.photos/200",
        link: "https://jalaj.netlify.app",
        bio: "Software Developer",
        followers: [],
        following: [
          {
            _id: "asassddsd243434",
            firstName: "Ruchi",
            lastName: "Gupta",
            username: "ruchi@gmail.com",
            password: "test1234",
            createdAt: "2022-03-21T10:12:12+05:30",
            updatedAt: "2022-05-14T18:10:33+05:30",
            userHandler: "ruchi",
            pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
            link: "https://ruchi.netlify.app",
            bio: "Fashion Designer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "2",
          },
          {
            _id: "asassddfdsfdgsd32323",
            firstName: "Raj",
            lastName: "Singh",
            username: "raj@gmail.com",
            password: "1234asdf",
            createdAt: "2022-05-12T08:30:12+05:30",
            updatedAt: "2022-05-14T18:11:48+05:30",
            userHandler: "raj",
            pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
            link: "https://raj.netlify.app",
            bio: "Web Designer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "3",
          },
        ],
        bookmarks: [],
        id: "1",
      },
      {
        _id: "asassddfd232fgfg323",
        firstName: "Tanvi",
        lastName: "Sharma",
        username: "tanvi@gmail.com",
        password: "1234asdf",
        createdAt: "2022-04-09T09:30:12+05:30",
        updatedAt: "2022-05-14T18:12:29+05:30",
        userHandler: "tanvi",
        pic: "https://robohash.org/rerumperferendisaccusamus.png?size=300x300&set=set1",
        link: "https://tanvi.netlify.app",
        bio: "Web Developer",
        followers: [],
        following: [],
        bookmarks: [],
        id: "4",
      },
      {
        _id: "asassddfd232fg23ssfdf",
        firstName: "Navodita",
        lastName: "Shah",
        username: "navj@gmail.com",
        password: "1234asdf",
        createdAt: "2022-02-10T09:30:12+05:30",
        updatedAt: "2022-05-16T18:11:01+05:30",
        userHandler: "navjj",
        pic: "https://randomuser.me/api/portraits/women/49.jpg",
        link: "https://navjj.netlify.app",
        bio: "Mobile Developer",
        followers: [],
        following: [],
        bookmarks: [],
        id: "5",
      },
      {
        _id: "asassddfdsfdgsd32323",
        firstName: "Raj",
        lastName: "Singh",
        username: "raj@gmail.com",
        password: "1234asdf",
        createdAt: "2022-05-12T08:30:12+05:30",
        updatedAt: "2022-05-16T18:14:29+05:30",
        userHandler: "raj",
        pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
        link: "https://raj.netlify.app",
        bio: "Web Designer",
        followers: [
          {
            _id: "asassdafdgdk",
            firstName: "Jalaj",
            lastName: "Gupta",
            username: "jalaj@gmail.com",
            password: "test1234",
            createdAt: "2022-01-25T10:38:12+05:30",
            updatedAt: "2022-05-16T18:11:07+05:30",
            userHandler: "jalaj",
            pic: "https://picsum.photos/200",
            link: "https://jalaj.netlify.app",
            bio: "Software Developer",
            followers: [],
            following: [
              {
                _id: "asassddsd243434",
                firstName: "Ruchi",
                lastName: "Gupta",
                username: "ruchi@gmail.com",
                password: "test1234",
                createdAt: "2022-03-21T10:12:12+05:30",
                updatedAt: "2022-05-14T18:10:33+05:30",
                userHandler: "ruchi",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                link: "https://ruchi.netlify.app",
                bio: "Fashion Designer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "2",
              },
            ],
            bookmarks: [],
            id: "1",
          },
        ],
        following: [
          {
            _id: "asassdafdgdk",
            firstName: "Jalaj",
            lastName: "Gupta",
            username: "jalaj@gmail.com",
            password: "test1234",
            createdAt: "2022-01-25T10:38:12+05:30",
            updatedAt: "2022-05-16T18:12:59+05:30",
            userHandler: "jalaj",
            pic: "https://picsum.photos/200",
            link: "https://jalaj.netlify.app",
            bio: "Software Developer",
            followers: [
              {
                _id: "asassddsd243434",
                firstName: "Ruchi",
                lastName: "Gupta",
                username: "ruchi@gmail.com",
                password: "test1234",
                createdAt: "2022-03-21T10:12:12+05:30",
                updatedAt: "2022-05-16T18:11:07+05:30",
                userHandler: "ruchi",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                link: "https://ruchi.netlify.app",
                bio: "Fashion Designer",
                followers: [
                  {
                    _id: "asassdafdgdk",
                    firstName: "Jalaj",
                    lastName: "Gupta",
                    username: "jalaj@gmail.com",
                    password: "test1234",
                    createdAt: "2022-01-25T10:38:12+05:30",
                    updatedAt: "2022-05-14T18:08:40+05:30",
                    userHandler: "jalaj",
                    pic: "https://picsum.photos/200",
                    link: "https://jalaj.netlify.app",
                    bio: "Software Developer",
                    followers: [],
                    following: [],
                    bookmarks: [],
                    id: "1",
                  },
                ],
                following: [],
                bookmarks: [],
                id: "2",
              },
            ],
            following: [
              {
                _id: "asassddsd243434",
                firstName: "Ruchi",
                lastName: "Gupta",
                username: "ruchi@gmail.com",
                password: "test1234",
                createdAt: "2022-03-21T10:12:12+05:30",
                updatedAt: "2022-05-14T18:10:33+05:30",
                userHandler: "ruchi",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                link: "https://ruchi.netlify.app",
                bio: "Fashion Designer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "2",
              },
              {
                _id: "asassddfdsfdgsd32323",
                firstName: "Raj",
                lastName: "Singh",
                username: "raj@gmail.com",
                password: "1234asdf",
                createdAt: "2022-05-12T08:30:12+05:30",
                updatedAt: "2022-05-14T18:11:48+05:30",
                userHandler: "raj",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
                link: "https://raj.netlify.app",
                bio: "Web Designer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "3",
              },
            ],
            bookmarks: [],
            id: "1",
          },
        ],
        bookmarks: [],
        id: "3",
      },
    ],
    bookmarks: [],
    id: "2",
  },
  {
    _id: "asassddfdsfdgsd32323",
    firstName: "Raj",
    lastName: "Singh",
    username: "raj@gmail.com",
    password: "1234asdf",
    createdAt: "2022-05-12T08:30:12+05:30",
    updatedAt: "2022-05-17T11:07:58+05:30",
    userHandler: "raj",
    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
    link: "https://raj.netlify.app",
    bio: "Web Designer",
    followers: [
      {
        _id: "asassdafdgdk",
        firstName: "Jalaj",
        lastName: "Gupta",
        username: "jalaj@gmail.com",
        password: "test1234",
        createdAt: "2022-01-25T10:38:12+05:30",
        updatedAt: "2022-05-16T18:11:07+05:30",
        userHandler: "jalaj",
        pic: "https://picsum.photos/200",
        link: "https://jalaj.netlify.app",
        bio: "Software Developer",
        followers: [],
        following: [
          {
            _id: "asassddsd243434",
            firstName: "Ruchi",
            lastName: "Gupta",
            username: "ruchi@gmail.com",
            password: "test1234",
            createdAt: "2022-03-21T10:12:12+05:30",
            updatedAt: "2022-05-14T18:10:33+05:30",
            userHandler: "ruchi",
            pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
            link: "https://ruchi.netlify.app",
            bio: "Fashion Designer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "2",
          },
        ],
        bookmarks: [],
        id: "1",
      },
      {
        _id: "asassddsd243434",
        firstName: "Ruchi",
        lastName: "Gupta",
        username: "ruchi@gmail.com",
        password: "test1234",
        createdAt: "2022-03-21T10:12:12+05:30",
        updatedAt: "2022-05-17T10:24:05+05:30",
        userHandler: "ruchi",
        pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
        link: "https://ruchi.netlify.app",
        bio: "Fashion Designer",
        followers: [
          {
            _id: "asassdafdgdk",
            firstName: "Jalaj",
            lastName: "Gupta",
            username: "jalaj@gmail.com",
            password: "test1234",
            createdAt: "2022-01-25T10:38:12+05:30",
            updatedAt: "2022-05-14T18:08:40+05:30",
            userHandler: "jalaj",
            pic: "https://picsum.photos/200",
            link: "https://jalaj.netlify.app",
            bio: "Software Developer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "1",
          },
        ],
        following: [
          {
            _id: "asassdafdgdk",
            firstName: "Jalaj",
            lastName: "Gupta",
            username: "jalaj@gmail.com",
            password: "test1234",
            createdAt: "2022-01-25T10:38:12+05:30",
            updatedAt: "2022-05-16T18:11:33+05:30",
            userHandler: "jalaj",
            pic: "https://picsum.photos/200",
            link: "https://jalaj.netlify.app",
            bio: "Software Developer",
            followers: [],
            following: [
              {
                _id: "asassddsd243434",
                firstName: "Ruchi",
                lastName: "Gupta",
                username: "ruchi@gmail.com",
                password: "test1234",
                createdAt: "2022-03-21T10:12:12+05:30",
                updatedAt: "2022-05-14T18:10:33+05:30",
                userHandler: "ruchi",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                link: "https://ruchi.netlify.app",
                bio: "Fashion Designer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "2",
              },
              {
                _id: "asassddfdsfdgsd32323",
                firstName: "Raj",
                lastName: "Singh",
                username: "raj@gmail.com",
                password: "1234asdf",
                createdAt: "2022-05-12T08:30:12+05:30",
                updatedAt: "2022-05-14T18:11:48+05:30",
                userHandler: "raj",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
                link: "https://raj.netlify.app",
                bio: "Web Designer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "3",
              },
            ],
            bookmarks: [],
            id: "1",
          },
          {
            _id: "asassddfd232fgfg323",
            firstName: "Tanvi",
            lastName: "Sharma",
            username: "tanvi@gmail.com",
            password: "1234asdf",
            createdAt: "2022-04-09T09:30:12+05:30",
            updatedAt: "2022-05-14T18:12:29+05:30",
            userHandler: "tanvi",
            pic: "https://robohash.org/rerumperferendisaccusamus.png?size=300x300&set=set1",
            link: "https://tanvi.netlify.app",
            bio: "Web Developer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "4",
          },
          {
            _id: "asassddfd232fg23ssfdf",
            firstName: "Navodita",
            lastName: "Shah",
            username: "navj@gmail.com",
            password: "1234asdf",
            createdAt: "2022-02-10T09:30:12+05:30",
            updatedAt: "2022-05-16T18:11:01+05:30",
            userHandler: "navjj",
            pic: "https://randomuser.me/api/portraits/women/49.jpg",
            link: "https://navjj.netlify.app",
            bio: "Mobile Developer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "5",
          },
        ],
        bookmarks: [],
        id: "2",
      },
    ],
    following: [
      {
        _id: "asassdafdgdk",
        firstName: "Jalaj",
        lastName: "Gupta",
        username: "jalaj@gmail.com",
        password: "test1234",
        createdAt: "2022-01-25T10:38:12+05:30",
        updatedAt: "2022-05-16T18:12:59+05:30",
        userHandler: "jalaj",
        pic: "https://picsum.photos/200",
        link: "https://jalaj.netlify.app",
        bio: "Software Developer",
        followers: [
          {
            _id: "asassddsd243434",
            firstName: "Ruchi",
            lastName: "Gupta",
            username: "ruchi@gmail.com",
            password: "test1234",
            createdAt: "2022-03-21T10:12:12+05:30",
            updatedAt: "2022-05-16T18:11:07+05:30",
            userHandler: "ruchi",
            pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
            link: "https://ruchi.netlify.app",
            bio: "Fashion Designer",
            followers: [
              {
                _id: "asassdafdgdk",
                firstName: "Jalaj",
                lastName: "Gupta",
                username: "jalaj@gmail.com",
                password: "test1234",
                createdAt: "2022-01-25T10:38:12+05:30",
                updatedAt: "2022-05-14T18:08:40+05:30",
                userHandler: "jalaj",
                pic: "https://picsum.photos/200",
                link: "https://jalaj.netlify.app",
                bio: "Software Developer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "1",
              },
            ],
            following: [],
            bookmarks: [],
            id: "2",
          },
        ],
        following: [
          {
            _id: "asassddsd243434",
            firstName: "Ruchi",
            lastName: "Gupta",
            username: "ruchi@gmail.com",
            password: "test1234",
            createdAt: "2022-03-21T10:12:12+05:30",
            updatedAt: "2022-05-14T18:10:33+05:30",
            userHandler: "ruchi",
            pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
            link: "https://ruchi.netlify.app",
            bio: "Fashion Designer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "2",
          },
          {
            _id: "asassddfdsfdgsd32323",
            firstName: "Raj",
            lastName: "Singh",
            username: "raj@gmail.com",
            password: "1234asdf",
            createdAt: "2022-05-12T08:30:12+05:30",
            updatedAt: "2022-05-14T18:11:48+05:30",
            userHandler: "raj",
            pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
            link: "https://raj.netlify.app",
            bio: "Web Designer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "3",
          },
        ],
        bookmarks: [],
        id: "1",
      },
      {
        _id: "asassddsd243434",
        firstName: "Ruchi",
        lastName: "Gupta",
        username: "ruchi@gmail.com",
        password: "test1234",
        createdAt: "2022-03-21T10:12:12+05:30",
        updatedAt: "2022-05-17T11:07:26+05:30",
        userHandler: "ruchi",
        pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
        link: "https://ruchi.netlify.app",
        bio: "Fashion Designer",
        followers: [
          {
            _id: "asassdafdgdk",
            firstName: "Jalaj",
            lastName: "Gupta",
            username: "jalaj@gmail.com",
            password: "test1234",
            createdAt: "2022-01-25T10:38:12+05:30",
            updatedAt: "2022-05-14T18:08:40+05:30",
            userHandler: "jalaj",
            pic: "https://picsum.photos/200",
            link: "https://jalaj.netlify.app",
            bio: "Software Developer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "1",
          },
          {
            _id: "asassddfd232fgfg323",
            firstName: "Tanvi",
            lastName: "Sharma",
            username: "tanvi@gmail.com",
            password: "1234asdf",
            createdAt: "2022-04-09T09:30:12+05:30",
            updatedAt: "2022-05-16T18:13:02+05:30",
            userHandler: "tanvi",
            pic: "https://robohash.org/rerumperferendisaccusamus.png?size=300x300&set=set1",
            link: "https://tanvi.netlify.app",
            bio: "Web Developer",
            followers: [
              {
                _id: "asassddsd243434",
                firstName: "Ruchi",
                lastName: "Gupta",
                username: "ruchi@gmail.com",
                password: "test1234",
                createdAt: "2022-03-21T10:12:12+05:30",
                updatedAt: "2022-05-16T18:12:59+05:30",
                userHandler: "ruchi",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                link: "https://ruchi.netlify.app",
                bio: "Fashion Designer",
                followers: [
                  {
                    _id: "asassdafdgdk",
                    firstName: "Jalaj",
                    lastName: "Gupta",
                    username: "jalaj@gmail.com",
                    password: "test1234",
                    createdAt: "2022-01-25T10:38:12+05:30",
                    updatedAt: "2022-05-14T18:08:40+05:30",
                    userHandler: "jalaj",
                    pic: "https://picsum.photos/200",
                    link: "https://jalaj.netlify.app",
                    bio: "Software Developer",
                    followers: [],
                    following: [],
                    bookmarks: [],
                    id: "1",
                  },
                ],
                following: [
                  {
                    _id: "asassdafdgdk",
                    firstName: "Jalaj",
                    lastName: "Gupta",
                    username: "jalaj@gmail.com",
                    password: "test1234",
                    createdAt: "2022-01-25T10:38:12+05:30",
                    updatedAt: "2022-05-16T18:11:33+05:30",
                    userHandler: "jalaj",
                    pic: "https://picsum.photos/200",
                    link: "https://jalaj.netlify.app",
                    bio: "Software Developer",
                    followers: [],
                    following: [
                      {
                        _id: "asassddsd243434",
                        firstName: "Ruchi",
                        lastName: "Gupta",
                        username: "ruchi@gmail.com",
                        password: "test1234",
                        createdAt: "2022-03-21T10:12:12+05:30",
                        updatedAt: "2022-05-14T18:10:33+05:30",
                        userHandler: "ruchi",
                        pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                        link: "https://ruchi.netlify.app",
                        bio: "Fashion Designer",
                        followers: [],
                        following: [],
                        bookmarks: [],
                        id: "2",
                      },
                      {
                        _id: "asassddfdsfdgsd32323",
                        firstName: "Raj",
                        lastName: "Singh",
                        username: "raj@gmail.com",
                        password: "1234asdf",
                        createdAt: "2022-05-12T08:30:12+05:30",
                        updatedAt: "2022-05-14T18:11:48+05:30",
                        userHandler: "raj",
                        pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
                        link: "https://raj.netlify.app",
                        bio: "Web Designer",
                        followers: [],
                        following: [],
                        bookmarks: [],
                        id: "3",
                      },
                    ],
                    bookmarks: [],
                    id: "1",
                  },
                ],
                bookmarks: [],
                id: "2",
              },
            ],
            following: [],
            bookmarks: [],
            id: "4",
          },
        ],
        following: [
          {
            _id: "asassdafdgdk",
            firstName: "Jalaj",
            lastName: "Gupta",
            username: "jalaj@gmail.com",
            password: "test1234",
            createdAt: "2022-01-25T10:38:12+05:30",
            updatedAt: "2022-05-16T18:11:33+05:30",
            userHandler: "jalaj",
            pic: "https://picsum.photos/200",
            link: "https://jalaj.netlify.app",
            bio: "Software Developer",
            followers: [],
            following: [
              {
                _id: "asassddsd243434",
                firstName: "Ruchi",
                lastName: "Gupta",
                username: "ruchi@gmail.com",
                password: "test1234",
                createdAt: "2022-03-21T10:12:12+05:30",
                updatedAt: "2022-05-14T18:10:33+05:30",
                userHandler: "ruchi",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                link: "https://ruchi.netlify.app",
                bio: "Fashion Designer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "2",
              },
              {
                _id: "asassddfdsfdgsd32323",
                firstName: "Raj",
                lastName: "Singh",
                username: "raj@gmail.com",
                password: "1234asdf",
                createdAt: "2022-05-12T08:30:12+05:30",
                updatedAt: "2022-05-14T18:11:48+05:30",
                userHandler: "raj",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
                link: "https://raj.netlify.app",
                bio: "Web Designer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "3",
              },
            ],
            bookmarks: [],
            id: "1",
          },
          {
            _id: "asassddfd232fgfg323",
            firstName: "Tanvi",
            lastName: "Sharma",
            username: "tanvi@gmail.com",
            password: "1234asdf",
            createdAt: "2022-04-09T09:30:12+05:30",
            updatedAt: "2022-05-14T18:12:29+05:30",
            userHandler: "tanvi",
            pic: "https://robohash.org/rerumperferendisaccusamus.png?size=300x300&set=set1",
            link: "https://tanvi.netlify.app",
            bio: "Web Developer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "4",
          },
          {
            _id: "asassddfd232fg23ssfdf",
            firstName: "Navodita",
            lastName: "Shah",
            username: "navj@gmail.com",
            password: "1234asdf",
            createdAt: "2022-02-10T09:30:12+05:30",
            updatedAt: "2022-05-16T18:11:01+05:30",
            userHandler: "navjj",
            pic: "https://randomuser.me/api/portraits/women/49.jpg",
            link: "https://navjj.netlify.app",
            bio: "Mobile Developer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "5",
          },
          {
            _id: "asassddfdsfdgsd32323",
            firstName: "Raj",
            lastName: "Singh",
            username: "raj@gmail.com",
            password: "1234asdf",
            createdAt: "2022-05-12T08:30:12+05:30",
            updatedAt: "2022-05-16T18:14:29+05:30",
            userHandler: "raj",
            pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
            link: "https://raj.netlify.app",
            bio: "Web Designer",
            followers: [
              {
                _id: "asassdafdgdk",
                firstName: "Jalaj",
                lastName: "Gupta",
                username: "jalaj@gmail.com",
                password: "test1234",
                createdAt: "2022-01-25T10:38:12+05:30",
                updatedAt: "2022-05-16T18:11:07+05:30",
                userHandler: "jalaj",
                pic: "https://picsum.photos/200",
                link: "https://jalaj.netlify.app",
                bio: "Software Developer",
                followers: [],
                following: [
                  {
                    _id: "asassddsd243434",
                    firstName: "Ruchi",
                    lastName: "Gupta",
                    username: "ruchi@gmail.com",
                    password: "test1234",
                    createdAt: "2022-03-21T10:12:12+05:30",
                    updatedAt: "2022-05-14T18:10:33+05:30",
                    userHandler: "ruchi",
                    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                    link: "https://ruchi.netlify.app",
                    bio: "Fashion Designer",
                    followers: [],
                    following: [],
                    bookmarks: [],
                    id: "2",
                  },
                ],
                bookmarks: [],
                id: "1",
              },
            ],
            following: [
              {
                _id: "asassdafdgdk",
                firstName: "Jalaj",
                lastName: "Gupta",
                username: "jalaj@gmail.com",
                password: "test1234",
                createdAt: "2022-01-25T10:38:12+05:30",
                updatedAt: "2022-05-16T18:12:59+05:30",
                userHandler: "jalaj",
                pic: "https://picsum.photos/200",
                link: "https://jalaj.netlify.app",
                bio: "Software Developer",
                followers: [
                  {
                    _id: "asassddsd243434",
                    firstName: "Ruchi",
                    lastName: "Gupta",
                    username: "ruchi@gmail.com",
                    password: "test1234",
                    createdAt: "2022-03-21T10:12:12+05:30",
                    updatedAt: "2022-05-16T18:11:07+05:30",
                    userHandler: "ruchi",
                    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                    link: "https://ruchi.netlify.app",
                    bio: "Fashion Designer",
                    followers: [
                      {
                        _id: "asassdafdgdk",
                        firstName: "Jalaj",
                        lastName: "Gupta",
                        username: "jalaj@gmail.com",
                        password: "test1234",
                        createdAt: "2022-01-25T10:38:12+05:30",
                        updatedAt: "2022-05-14T18:08:40+05:30",
                        userHandler: "jalaj",
                        pic: "https://picsum.photos/200",
                        link: "https://jalaj.netlify.app",
                        bio: "Software Developer",
                        followers: [],
                        following: [],
                        bookmarks: [],
                        id: "1",
                      },
                    ],
                    following: [],
                    bookmarks: [],
                    id: "2",
                  },
                ],
                following: [
                  {
                    _id: "asassddsd243434",
                    firstName: "Ruchi",
                    lastName: "Gupta",
                    username: "ruchi@gmail.com",
                    password: "test1234",
                    createdAt: "2022-03-21T10:12:12+05:30",
                    updatedAt: "2022-05-14T18:10:33+05:30",
                    userHandler: "ruchi",
                    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                    link: "https://ruchi.netlify.app",
                    bio: "Fashion Designer",
                    followers: [],
                    following: [],
                    bookmarks: [],
                    id: "2",
                  },
                  {
                    _id: "asassddfdsfdgsd32323",
                    firstName: "Raj",
                    lastName: "Singh",
                    username: "raj@gmail.com",
                    password: "1234asdf",
                    createdAt: "2022-05-12T08:30:12+05:30",
                    updatedAt: "2022-05-14T18:11:48+05:30",
                    userHandler: "raj",
                    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
                    link: "https://raj.netlify.app",
                    bio: "Web Designer",
                    followers: [],
                    following: [],
                    bookmarks: [],
                    id: "3",
                  },
                ],
                bookmarks: [],
                id: "1",
              },
            ],
            bookmarks: [],
            id: "3",
          },
        ],
        bookmarks: [],
        id: "2",
      },
    ],
    bookmarks: [],
    id: "3",
  },
  {
    _id: "asassddfd232fgfg323",
    firstName: "Tanvi",
    lastName: "Sharma",
    username: "tanvi@gmail.com",
    password: "1234asdf",
    createdAt: "2022-04-09T09:30:12+05:30",
    updatedAt: "2022-05-17T11:07:27+05:30",
    userHandler: "tanvi",
    pic: "https://robohash.org/rerumperferendisaccusamus.png?size=300x300&set=set1",
    link: "https://tanvi.netlify.app",
    bio: "Web Developer",
    followers: [
      {
        _id: "asassddsd243434",
        firstName: "Ruchi",
        lastName: "Gupta",
        username: "ruchi@gmail.com",
        password: "test1234",
        createdAt: "2022-03-21T10:12:12+05:30",
        updatedAt: "2022-05-16T18:12:59+05:30",
        userHandler: "ruchi",
        pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
        link: "https://ruchi.netlify.app",
        bio: "Fashion Designer",
        followers: [
          {
            _id: "asassdafdgdk",
            firstName: "Jalaj",
            lastName: "Gupta",
            username: "jalaj@gmail.com",
            password: "test1234",
            createdAt: "2022-01-25T10:38:12+05:30",
            updatedAt: "2022-05-14T18:08:40+05:30",
            userHandler: "jalaj",
            pic: "https://picsum.photos/200",
            link: "https://jalaj.netlify.app",
            bio: "Software Developer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "1",
          },
        ],
        following: [
          {
            _id: "asassdafdgdk",
            firstName: "Jalaj",
            lastName: "Gupta",
            username: "jalaj@gmail.com",
            password: "test1234",
            createdAt: "2022-01-25T10:38:12+05:30",
            updatedAt: "2022-05-16T18:11:33+05:30",
            userHandler: "jalaj",
            pic: "https://picsum.photos/200",
            link: "https://jalaj.netlify.app",
            bio: "Software Developer",
            followers: [],
            following: [
              {
                _id: "asassddsd243434",
                firstName: "Ruchi",
                lastName: "Gupta",
                username: "ruchi@gmail.com",
                password: "test1234",
                createdAt: "2022-03-21T10:12:12+05:30",
                updatedAt: "2022-05-14T18:10:33+05:30",
                userHandler: "ruchi",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                link: "https://ruchi.netlify.app",
                bio: "Fashion Designer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "2",
              },
              {
                _id: "asassddfdsfdgsd32323",
                firstName: "Raj",
                lastName: "Singh",
                username: "raj@gmail.com",
                password: "1234asdf",
                createdAt: "2022-05-12T08:30:12+05:30",
                updatedAt: "2022-05-14T18:11:48+05:30",
                userHandler: "raj",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
                link: "https://raj.netlify.app",
                bio: "Web Designer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "3",
              },
            ],
            bookmarks: [],
            id: "1",
          },
        ],
        bookmarks: [],
        id: "2",
      },
    ],
    following: [
      {
        _id: "asassddsd243434",
        firstName: "Ruchi",
        lastName: "Gupta",
        username: "ruchi@gmail.com",
        password: "test1234",
        createdAt: "2022-03-21T10:12:12+05:30",
        updatedAt: "2022-05-17T11:05:59+05:30",
        userHandler: "ruchi",
        pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
        link: "https://ruchi.netlify.app",
        bio: "Fashion Designer",
        followers: [
          {
            _id: "asassdafdgdk",
            firstName: "Jalaj",
            lastName: "Gupta",
            username: "jalaj@gmail.com",
            password: "test1234",
            createdAt: "2022-01-25T10:38:12+05:30",
            updatedAt: "2022-05-14T18:08:40+05:30",
            userHandler: "jalaj",
            pic: "https://picsum.photos/200",
            link: "https://jalaj.netlify.app",
            bio: "Software Developer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "1",
          },
        ],
        following: [
          {
            _id: "asassdafdgdk",
            firstName: "Jalaj",
            lastName: "Gupta",
            username: "jalaj@gmail.com",
            password: "test1234",
            createdAt: "2022-01-25T10:38:12+05:30",
            updatedAt: "2022-05-16T18:11:33+05:30",
            userHandler: "jalaj",
            pic: "https://picsum.photos/200",
            link: "https://jalaj.netlify.app",
            bio: "Software Developer",
            followers: [],
            following: [
              {
                _id: "asassddsd243434",
                firstName: "Ruchi",
                lastName: "Gupta",
                username: "ruchi@gmail.com",
                password: "test1234",
                createdAt: "2022-03-21T10:12:12+05:30",
                updatedAt: "2022-05-14T18:10:33+05:30",
                userHandler: "ruchi",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                link: "https://ruchi.netlify.app",
                bio: "Fashion Designer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "2",
              },
              {
                _id: "asassddfdsfdgsd32323",
                firstName: "Raj",
                lastName: "Singh",
                username: "raj@gmail.com",
                password: "1234asdf",
                createdAt: "2022-05-12T08:30:12+05:30",
                updatedAt: "2022-05-14T18:11:48+05:30",
                userHandler: "raj",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
                link: "https://raj.netlify.app",
                bio: "Web Designer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "3",
              },
            ],
            bookmarks: [],
            id: "1",
          },
          {
            _id: "asassddfd232fgfg323",
            firstName: "Tanvi",
            lastName: "Sharma",
            username: "tanvi@gmail.com",
            password: "1234asdf",
            createdAt: "2022-04-09T09:30:12+05:30",
            updatedAt: "2022-05-14T18:12:29+05:30",
            userHandler: "tanvi",
            pic: "https://robohash.org/rerumperferendisaccusamus.png?size=300x300&set=set1",
            link: "https://tanvi.netlify.app",
            bio: "Web Developer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "4",
          },
          {
            _id: "asassddfd232fg23ssfdf",
            firstName: "Navodita",
            lastName: "Shah",
            username: "navj@gmail.com",
            password: "1234asdf",
            createdAt: "2022-02-10T09:30:12+05:30",
            updatedAt: "2022-05-16T18:11:01+05:30",
            userHandler: "navjj",
            pic: "https://randomuser.me/api/portraits/women/49.jpg",
            link: "https://navjj.netlify.app",
            bio: "Mobile Developer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "5",
          },
          {
            _id: "asassddfdsfdgsd32323",
            firstName: "Raj",
            lastName: "Singh",
            username: "raj@gmail.com",
            password: "1234asdf",
            createdAt: "2022-05-12T08:30:12+05:30",
            updatedAt: "2022-05-16T18:14:29+05:30",
            userHandler: "raj",
            pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
            link: "https://raj.netlify.app",
            bio: "Web Designer",
            followers: [
              {
                _id: "asassdafdgdk",
                firstName: "Jalaj",
                lastName: "Gupta",
                username: "jalaj@gmail.com",
                password: "test1234",
                createdAt: "2022-01-25T10:38:12+05:30",
                updatedAt: "2022-05-16T18:11:07+05:30",
                userHandler: "jalaj",
                pic: "https://picsum.photos/200",
                link: "https://jalaj.netlify.app",
                bio: "Software Developer",
                followers: [],
                following: [
                  {
                    _id: "asassddsd243434",
                    firstName: "Ruchi",
                    lastName: "Gupta",
                    username: "ruchi@gmail.com",
                    password: "test1234",
                    createdAt: "2022-03-21T10:12:12+05:30",
                    updatedAt: "2022-05-14T18:10:33+05:30",
                    userHandler: "ruchi",
                    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                    link: "https://ruchi.netlify.app",
                    bio: "Fashion Designer",
                    followers: [],
                    following: [],
                    bookmarks: [],
                    id: "2",
                  },
                ],
                bookmarks: [],
                id: "1",
              },
            ],
            following: [
              {
                _id: "asassdafdgdk",
                firstName: "Jalaj",
                lastName: "Gupta",
                username: "jalaj@gmail.com",
                password: "test1234",
                createdAt: "2022-01-25T10:38:12+05:30",
                updatedAt: "2022-05-16T18:12:59+05:30",
                userHandler: "jalaj",
                pic: "https://picsum.photos/200",
                link: "https://jalaj.netlify.app",
                bio: "Software Developer",
                followers: [
                  {
                    _id: "asassddsd243434",
                    firstName: "Ruchi",
                    lastName: "Gupta",
                    username: "ruchi@gmail.com",
                    password: "test1234",
                    createdAt: "2022-03-21T10:12:12+05:30",
                    updatedAt: "2022-05-16T18:11:07+05:30",
                    userHandler: "ruchi",
                    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                    link: "https://ruchi.netlify.app",
                    bio: "Fashion Designer",
                    followers: [
                      {
                        _id: "asassdafdgdk",
                        firstName: "Jalaj",
                        lastName: "Gupta",
                        username: "jalaj@gmail.com",
                        password: "test1234",
                        createdAt: "2022-01-25T10:38:12+05:30",
                        updatedAt: "2022-05-14T18:08:40+05:30",
                        userHandler: "jalaj",
                        pic: "https://picsum.photos/200",
                        link: "https://jalaj.netlify.app",
                        bio: "Software Developer",
                        followers: [],
                        following: [],
                        bookmarks: [],
                        id: "1",
                      },
                    ],
                    following: [],
                    bookmarks: [],
                    id: "2",
                  },
                ],
                following: [
                  {
                    _id: "asassddsd243434",
                    firstName: "Ruchi",
                    lastName: "Gupta",
                    username: "ruchi@gmail.com",
                    password: "test1234",
                    createdAt: "2022-03-21T10:12:12+05:30",
                    updatedAt: "2022-05-14T18:10:33+05:30",
                    userHandler: "ruchi",
                    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                    link: "https://ruchi.netlify.app",
                    bio: "Fashion Designer",
                    followers: [],
                    following: [],
                    bookmarks: [],
                    id: "2",
                  },
                  {
                    _id: "asassddfdsfdgsd32323",
                    firstName: "Raj",
                    lastName: "Singh",
                    username: "raj@gmail.com",
                    password: "1234asdf",
                    createdAt: "2022-05-12T08:30:12+05:30",
                    updatedAt: "2022-05-14T18:11:48+05:30",
                    userHandler: "raj",
                    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
                    link: "https://raj.netlify.app",
                    bio: "Web Designer",
                    followers: [],
                    following: [],
                    bookmarks: [],
                    id: "3",
                  },
                ],
                bookmarks: [],
                id: "1",
              },
            ],
            bookmarks: [],
            id: "3",
          },
        ],
        bookmarks: [],
        id: "2",
      },
    ],
    bookmarks: [],
    id: "4",
  },
  {
    _id: "asassddfd232fg23ssfdf",
    firstName: "Navodita",
    lastName: "Shah",
    username: "navj@gmail.com",
    password: "1234asdf",
    createdAt: "2022-02-10T09:30:12+05:30",
    updatedAt: "2022-05-17T10:24:04+05:30",
    userHandler: "navjj",
    pic: "https://randomuser.me/api/portraits/women/49.jpg",
    link: "https://navjj.netlify.app",
    bio: "Mobile Developer",
    followers: [
      {
        _id: "asassddsd243434",
        firstName: "Ruchi",
        lastName: "Gupta",
        username: "ruchi@gmail.com",
        password: "test1234",
        createdAt: "2022-03-21T10:12:12+05:30",
        updatedAt: "2022-05-16T18:13:22+05:30",
        userHandler: "ruchi",
        pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
        link: "https://ruchi.netlify.app",
        bio: "Fashion Designer",
        followers: [
          {
            _id: "asassdafdgdk",
            firstName: "Jalaj",
            lastName: "Gupta",
            username: "jalaj@gmail.com",
            password: "test1234",
            createdAt: "2022-01-25T10:38:12+05:30",
            updatedAt: "2022-05-14T18:08:40+05:30",
            userHandler: "jalaj",
            pic: "https://picsum.photos/200",
            link: "https://jalaj.netlify.app",
            bio: "Software Developer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "1",
          },
        ],
        following: [
          {
            _id: "asassdafdgdk",
            firstName: "Jalaj",
            lastName: "Gupta",
            username: "jalaj@gmail.com",
            password: "test1234",
            createdAt: "2022-01-25T10:38:12+05:30",
            updatedAt: "2022-05-16T18:11:33+05:30",
            userHandler: "jalaj",
            pic: "https://picsum.photos/200",
            link: "https://jalaj.netlify.app",
            bio: "Software Developer",
            followers: [],
            following: [
              {
                _id: "asassddsd243434",
                firstName: "Ruchi",
                lastName: "Gupta",
                username: "ruchi@gmail.com",
                password: "test1234",
                createdAt: "2022-03-21T10:12:12+05:30",
                updatedAt: "2022-05-14T18:10:33+05:30",
                userHandler: "ruchi",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                link: "https://ruchi.netlify.app",
                bio: "Fashion Designer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "2",
              },
              {
                _id: "asassddfdsfdgsd32323",
                firstName: "Raj",
                lastName: "Singh",
                username: "raj@gmail.com",
                password: "1234asdf",
                createdAt: "2022-05-12T08:30:12+05:30",
                updatedAt: "2022-05-14T18:11:48+05:30",
                userHandler: "raj",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
                link: "https://raj.netlify.app",
                bio: "Web Designer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "3",
              },
            ],
            bookmarks: [],
            id: "1",
          },
          {
            _id: "asassddfd232fgfg323",
            firstName: "Tanvi",
            lastName: "Sharma",
            username: "tanvi@gmail.com",
            password: "1234asdf",
            createdAt: "2022-04-09T09:30:12+05:30",
            updatedAt: "2022-05-14T18:12:29+05:30",
            userHandler: "tanvi",
            pic: "https://robohash.org/rerumperferendisaccusamus.png?size=300x300&set=set1",
            link: "https://tanvi.netlify.app",
            bio: "Web Developer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "4",
          },
        ],
        bookmarks: [],
        id: "2",
      },
    ],
    following: [],
    bookmarks: [],
    id: "5",
  },
  {
    _id: "asassddfasadsdgfssfdf",
    firstName: "Harshita",
    lastName: "Sharma",
    username: "hsmcute@gmail.com",
    password: "1234asdf09",
    createdAt: "2022-02-17T09:30:12+05:30",
    updatedAt: "2022-05-17T10:33:36+05:30",
    userHandler: "hsmcute",
    pic: "https://randomuser.me/api/portraits/women/22.jpg",
    link: "https://hsmcute.netlify.app",
    bio: "SDE-3 at Google",
    followers: [
      {
        _id: "asassdafdgdk",
        firstName: "Jalaj",
        lastName: "Gupta",
        username: "jalaj@gmail.com",
        password: "test1234",
        createdAt: "2022-01-25T10:38:12+05:30",
        updatedAt: "2022-05-16T18:14:29+05:30",
        userHandler: "jalaj",
        pic: "https://picsum.photos/200",
        link: "https://jalaj.netlify.app",
        bio: "Software Developer",
        followers: [
          {
            _id: "asassddsd243434",
            firstName: "Ruchi",
            lastName: "Gupta",
            username: "ruchi@gmail.com",
            password: "test1234",
            createdAt: "2022-03-21T10:12:12+05:30",
            updatedAt: "2022-05-16T18:11:07+05:30",
            userHandler: "ruchi",
            pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
            link: "https://ruchi.netlify.app",
            bio: "Fashion Designer",
            followers: [
              {
                _id: "asassdafdgdk",
                firstName: "Jalaj",
                lastName: "Gupta",
                username: "jalaj@gmail.com",
                password: "test1234",
                createdAt: "2022-01-25T10:38:12+05:30",
                updatedAt: "2022-05-14T18:08:40+05:30",
                userHandler: "jalaj",
                pic: "https://picsum.photos/200",
                link: "https://jalaj.netlify.app",
                bio: "Software Developer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "1",
              },
            ],
            following: [],
            bookmarks: [],
            id: "2",
          },
          {
            _id: "asassddfdsfdgsd32323",
            firstName: "Raj",
            lastName: "Singh",
            username: "raj@gmail.com",
            password: "1234asdf",
            createdAt: "2022-05-12T08:30:12+05:30",
            updatedAt: "2022-05-16T18:11:32+05:30",
            userHandler: "raj",
            pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
            link: "https://raj.netlify.app",
            bio: "Web Designer",
            followers: [
              {
                _id: "asassdafdgdk",
                firstName: "Jalaj",
                lastName: "Gupta",
                username: "jalaj@gmail.com",
                password: "test1234",
                createdAt: "2022-01-25T10:38:12+05:30",
                updatedAt: "2022-05-16T18:11:07+05:30",
                userHandler: "jalaj",
                pic: "https://picsum.photos/200",
                link: "https://jalaj.netlify.app",
                bio: "Software Developer",
                followers: [],
                following: [
                  {
                    _id: "asassddsd243434",
                    firstName: "Ruchi",
                    lastName: "Gupta",
                    username: "ruchi@gmail.com",
                    password: "test1234",
                    createdAt: "2022-03-21T10:12:12+05:30",
                    updatedAt: "2022-05-14T18:10:33+05:30",
                    userHandler: "ruchi",
                    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                    link: "https://ruchi.netlify.app",
                    bio: "Fashion Designer",
                    followers: [],
                    following: [],
                    bookmarks: [],
                    id: "2",
                  },
                ],
                bookmarks: [],
                id: "1",
              },
            ],
            following: [],
            bookmarks: [],
            id: "3",
          },
        ],
        following: [
          {
            _id: "asassddsd243434",
            firstName: "Ruchi",
            lastName: "Gupta",
            username: "ruchi@gmail.com",
            password: "test1234",
            createdAt: "2022-03-21T10:12:12+05:30",
            updatedAt: "2022-05-14T18:10:33+05:30",
            userHandler: "ruchi",
            pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
            link: "https://ruchi.netlify.app",
            bio: "Fashion Designer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "2",
          },
          {
            _id: "asassddfdsfdgsd32323",
            firstName: "Raj",
            lastName: "Singh",
            username: "raj@gmail.com",
            password: "1234asdf",
            createdAt: "2022-05-12T08:30:12+05:30",
            updatedAt: "2022-05-14T18:11:48+05:30",
            userHandler: "raj",
            pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
            link: "https://raj.netlify.app",
            bio: "Web Designer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "3",
          },
        ],
        bookmarks: [],
        id: "1",
      },
    ],
    following: [],
    bookmarks: [],
    id: "6",
  },
  {
    _id: "asassddfd23dgdg334df",
    firstName: "Himanshu",
    lastName: "Mittal",
    username: "himmm@gmail.com",
    password: "1234asdf09",
    createdAt: "2022-03-19T09:30:12+05:30",
    updatedAt: "2022-05-16T18:11:01+05:30",
    userHandler: "himmm",
    pic: "https://randomuser.me/api/portraits/lego/3.jpg",
    link: "https://himmmm.netlify.app",
    bio: "Principal Engineer at Google",
    followers: [],
    following: [],
    bookmarks: [],
    id: "7",
  },
  {
    _id: "fdgdg5590sd90",
    firstName: "Test",
    lastName: "Jha",
    username: "test@gmail.com",
    password: "1234asdf",
    createdAt: "2022-03-20T09:30:12+05:30",
    updatedAt: "2022-05-16T18:11:01+05:30",
    userHandler: "test",
    pic: "https://randomuser.me/api/portraits/lego/6.jpg",
    link: "https://test.netlify.app",
    bio: "SDE-II at Groww",
    followers: [],
    following: [],
    bookmarks: [],
    id: "8",
  },
];
